AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using
  Amazon API Gateway.
Resources:
  urlfetcher:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: >-
        A simple backend (read/write to DynamoDB) with a RESTful API endpoint
        using Amazon API Gateway.
      MemorySize: 128
      Timeout: 2
      Role: 'arn:aws:iam::846448025575:role/service-role/url-fetcher'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /url-fetcher
            Method: ANY
      Tags:
        'lambda-console:blueprint': microservice-http-endpoint