name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Install packages
          run: yarn install
        - name: Set Creds
          run: git config user.name "<username>" && git config user.email "<email>"
        - name: Deploy
          run: yarn run deploy